### ISSUE TITLE
Llama3 70B doesn't run well

### ISSUE THREAD

**Issue by Lyy-iiis** [Lyy-iiis/LLM_project#1]
It doesn't clear memory after the function returns. Besides, we don't know the order that server and client starts, which may create  some strange issues. @HACLINE @qiaosungithub

**Comment by Hidden-Hyperparameter** [comment]
We seems to encounter the same problem. When running Llama 3 70B in python files using 

`os.system(f"/share/ollama/ollama run llama3:70b < {QUERY_TXT} > {QUERY_TAG}")`

the program get stucked with no outputs on the screen. Will be pleasured if you can fix it!

**Comment by Lyy-iiis** [comment]
It seems we don't have same problem, and i think it can be fixed by me

**Comment by Lyy-iiis** [comment]
Thanks Xibo! This bug is fixed
